## Import the library and give it an alias

In [5]:
import numpy as np

## Create an array with 3 zeros:

In [6]:
a = np.zeros(3)
a

array([0., 0., 0.])

## Create a 3 rows X 4 columns array (martix) of ones:

In [18]:
b = np.ones([3,4])
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Create an array from a list

In [43]:
c = np.array([2,3,4,5])
c

array([2, 3, 4, 5])

In [47]:
type(c) # type of numpy arrays. 

numpy.ndarray

## See the shape and the size of an array:

In [19]:
b.shape # row-col

(3, 4)

In [20]:
b.size

12

## Reshape an array by changing the shape property (size should be the same)

In [21]:
ar = np.zeros([2,3])
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
ar.shape = (1,6)
ar

array([[0., 0., 0., 0., 0., 0.]])

In [23]:
ar.shape = (3,2)
ar

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Create a range with a specific number of elements step:

In [39]:
# np.linspace(start, end, number of elements)
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [40]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [14]:
c.size

9

In [31]:
d =  np.zeros(10,)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
d.size

10

In [33]:
d.shape = (10,1)

In [34]:
d

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

Exercise: 

In [35]:
my_list = [3,5,7,9]
my_array = np.array(my_list)
my_array

array([3, 5, 7, 9])

In [36]:
my_list = [[2,4,6,8],[3,5,7,9]]
my_array = np.array(my_list)
my_array

array([[2, 4, 6, 8],
       [3, 5, 7, 9]])

In [51]:
myarray.

Object `my_array.shape` not found.


In [38]:
?my_array

Type:        ndarray
String form:
[[2 4 6 8]
 [3 5 7 9]]
Length:      2
File:        ~/Repos/geogeek-workshop/.venv/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type

In [ ]:
# Indexing and Slicing:

In [58]:
d = np.array([2,4,6,8,10])
print(d[0])
print(d[-1])
print(d[1:4])

2
10
[4 6 8]


## Question: What is the difference between np.array([[0,0,0,0]]) and np.array([0,0,0,0]):

In [38]:
import numpy as np
a1 = np.array([[0,0,0,0]])
a2 = np.array([0,0,0,0])
print(a1)
print(a2)

[[0 0 0 0]]
[0 0 0 0]


In [36]:
print(a1.shape)
print(a2.shape)

(1, 4)
(4,)


In [50]:
#from skimage import io
!pip install scikit-image

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 12.2 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 13.6 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.2/313.2 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.9/222.9 kB 10.9 MB/s eta 0:00:00
  Using cached Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl (3.3 MB)
  Attempting uninstall: pillow
    Found existing installation: Pillow 10.1.0
    Uninstalling Pillow-10.1.0:
      Successfully uninstalled Pillow-10.1.0

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip


# RASTERIO

In [35]:
import rasterio
dataset = rasterio.open("/Users/gina/Downloads/R_25GZ1.TIF")
dataset.bounds

BoundingBox(left=120000.0, bottom=475000.0, right=125000.0, top=481250.0)